"""Version identity for ITACA (REQ-92, DD-21, DD-38, DD-48, DD-49).

The resolution order, which is the whole of what this module does:

1. ``itaca/core/_version.py``, generated by ``setuptools-scm`` at build
   time and shipped inside the distribution;
2. failing that, the installed distribution metadata;
3. failing both, raise. A version that cannot be resolved is not
   guessed and is never null, because either would be stamped into
   Provenance and into ``.itc`` archives as though it were a fact.

The version is DERIVED FROM THE REPOSITORY and never written here. A
commit carrying the release tag ``vX.Y.Z`` builds as exactly ``X.Y.Z``;
every other commit builds as ``X.Y.Z.devN``, naming the release being
worked toward, with ``N`` the number of commits since the last tag.
Until 0.2.0 this module held a literal and an sdist built from the M1
seam was named ``itaca-0.1.0.tar.gz`` (``ITACA-004``).

WHY THE FILE COMES FIRST, and what that does NOT fix, is DD-48 and
DD-49. In short: ``importlib.metadata`` finds a distribution by scanning
``sys.path``, the working directory is on ``sys.path``, and a stray
``itaca.egg-info/`` therefore decided what the library said about
itself. Two residuals survive and are recorded in DD-49 rather than
here, because both were measured once and restating them in four places
is how they go stale: an editable checkout reports the version of its
last BUILD, and a tree that has never been built has no version file
and is still shadowable.
"""

from __future__ import annotations

import warnings

from itaca.core.errors import VersionResolutionError


def _from_version_file() -> str | None:
    """Return the version ``setuptools-scm`` wrote into the package.

    Gitignored, because it is generated, so a clone that has never been
    built does not have it and this returns ``None``.

    EVERY failure returns ``None`` rather than propagating, and the
    breadth is deliberate. This file is generated by a build, so it can
    exist and be unusable: an interrupted or truncated write, or a
    template using syntax the running interpreter rejects. It is also
    read at ``import itaca`` time and is now FIRST rather than second, so
    a narrow ``except ImportError`` would let a ``SyntaxError`` out of
    the import statement itself and make the library unimportable, with
    a raw traceback instead of the three-part error this module exists
    to give, and without ever reaching the metadata path that would have
    answered correctly. Measured before this was widened: a truncated
    ``_version.py`` produced ``SyntaxError: '(' was never closed`` from
    ``import itaca``.
    """
    try:
        from itaca.core._version import __version__ as built
    except ImportError:
        return None
    except Exception as error:
        # Present and unusable, which is different from absent and must
        # not look the same. Falling through silently would hand the
        # answer to the metadata path, the one this module documents as
        # decidable by the working directory, and stamp it into
        # Provenance as a fact. A version that cannot be read is not
        # guessed past without saying so.
        warnings.warn(
            f"itaca/core/_version.py exists and could not be read "
            f"({type(error).__name__}: {error}); the version is falling back "
            f"to the installed distribution metadata, which may belong to a "
            f"different tree. Rebuild or reinstall with pip install -e . to "
            f"regenerate it (REQ-92, DD-49).",
            RuntimeWarning,
            stacklevel=2,
        )
        return None
    return str(built) or None


def _from_distribution_metadata() -> str | None:
    """Return the installed distribution's version, if one can be read.

    Returns ``None`` rather than raising for BOTH ways this can fail:
    no distribution at all, and a distribution whose metadata parses and
    carries no ``Version:`` field. The second returns ``None`` from
    ``version()`` at runtime while typeshed declares ``str``, so
    ``mypy --strict`` cannot see it and only this guard can.
    """
    from importlib.metadata import PackageNotFoundError, version

    try:
        found: str | None = version("itaca")
    except PackageNotFoundError:
        return None
    return found or None


def _resolve() -> str:
    """Return the version the build recorded, or fail loud."""
    resolved = _from_version_file() or _from_distribution_metadata()
    if resolved is None:
        raise VersionResolutionError(
            "itaca.core.version",
            "neither the generated version file nor the installed "
            "distribution metadata for itaca yielded a version, so nothing "
            "can be stamped into Provenance or a .itc archive",
            "install the package with pip install -e . so the version is "
            "derived from the repository tag; a source tree that was never "
            "installed has no version to report (REQ-92)",
        )
    return resolved


__version__ = _resolve()
